### ISSUE TITLE
Cannot use setup due to 401 on joined-1.13.1.pom

### ISSUE THREAD

**Issue by milse113** [Hexeption/PRE-MCP#3]
I am attempting to use MCP 1.13.1 but whenever I attempt to run `setup` I end up getting an error:
```Could not HEAD 'http://repo.strezz.org/artifactory/list/Strezz-Central/net/minecraft/joined/1.13.1/joined-1.13.1.pom'. Received status code 401 from server: Unauthorized```

I am not sure why this is happening, but I cannot seem to fix it.

**Comment by Ezb2661** [comment]
I am also having this error,  I am guessing hex either removed or changed permissions to the file on the server because if you try to open the URL it will give you a permission error.

**Comment by FakeZane** [comment]
I suggest replacing ``strezz.org`` with ``hexeption.co.uk`` , it should work

**Comment by wisys** [comment]
I can confirm that @FakeZane 's response fixes the repository issue by going into root\build.gradle and changing the old domain with the new one. Thank you!
