### ISSUE TITLE
Received status code 503 from server: Service Temporarily Unavailable

### ISSUE THREAD

**Issue by ahmed605** [Hexeption/PRE-MCP#6]
Received status code 503 from server: Service Temporarily Unavailable from https://repo.hexeption.co.uk/

**Comment by WinMister332** [comment]
In InteliJ the full error states: `Could not GET 'http://repo.hexeption.co.uk/artifactory/list/Strezz-Central/net/minecraftforge/Srg2Source/maven-metadata.xml'. Received status code 503 from server: Service Temporarily Unavailable`
When entering the specified URL into a web-browser it retruns:
`{
  "errors" : [ {
    "status" : 404,
    "message" : "Not Found"
  } ]
}`
Which would leave one to assume @Hexeption likely removed the maven repository from the specified source rendering this repository and it's following files useless.
(However, I hope that it's actually just an error and not the case that he just doesn't care about the files anymore.)

**Comment by ahmed605** [comment]
> In InteliJ the full error states: `Could not GET 'http://repo.hexeption.co.uk/artifactory/list/Strezz-Central/net/minecraftforge/Srg2Source/maven-metadata.xml'. Received status code 503 from server: Service Temporarily Unavailable`
> When entering the specified URL into a web-browser it retruns:
> `{ "errors" : [ { "status" : 404, "message" : "Not Found" } ] }`
> Which would leave one to assume @Hexeption likely removed the maven repository from the specified source rendering this repository and it's following files useless.
> (However, I hope that it's actually just an error and not the case that he just doesn't care about the files anymore.)

I have fixed it and upgrade it to 1.14.2 link: https://github.com/ahmed605/PRE-MCP
